In [7]:
# Введем матрицу изображения
import numpy as np
m1 = '100001 011100 011100 111111 001100 101101'
image = np.array([tuple(map(float, i)) for i in m1.split()])

In [10]:
# Вводим матрицу фильтра
filtr = '010 111 010'
mask = np.array([tuple(map(float, _)) for _ in filtr.split()])

In [13]:
# Вводим значение шага или stride
stride_x = 1
stride_y = 1 

In [14]:
# Получаем итоговый размер матрицы 
result = np.zeros(((image.shape[0] - mask.shape[0] + stride_y) // stride_y,
                   (image.shape[1] - mask.shape[1] + stride_x) // stride_x))

In [21]:
#Применим свертку
for i in range(result.shape[0]):
    for j in range(result.shape[1]):
        mtx = image[i * stride_y:i * stride_y + mask.shape[0], j * stride_x:j * stride_x + mask.shape[1]]
        result[i, j] = (mtx * mask).sum()

In [23]:
print(result)

[[3. 4. 3. 1.]
 [4. 5. 4. 2.]
 [4. 5. 5. 3.]
 [2. 4. 4. 2.]]
